# Site settings
title: ninepoints
email: jeremycong@gmail.com
author: Jeremy Ong
description: 'C++, graphics, deep learning, multithreading, Vulkan, OpenGL, DirectX, Math, compilers, and more'
baseurl: ''
url: 'https://jeremyong.com'
date_format: '%b %-d, %Y'
header_pages:
  - about.md
  - bookshelf.md

# Google services
google_analytics: UA-10576233-1

# Optional features
show_related_posts: true
show_post_footers: true
show_social_icons: true
ajaxify_contact_form: true

# Social icons
github_username: jeremyong
twitter_username: m_ninepoints
linkedin_username: jeremycong

text:
  og_locale: 'en_US'

# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
paginate: 4
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-scholar
  - jekyll-feed
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
